# Site settings
title: "TestCafe"
baseurl: "/testcafe" 
url: "http://localhost:8080" 
  
# Build settings
markdown: redcarpet
highlighter: null
redcarpet:
  extensions: ["tables"]
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

# Blog
excerpt_separator: "<!--more-->"
