# Site settings
title: "TestCafe"
baseurl: "/testcafe" 
url: "https://devexpress.github.io" 
  
# Build settings
markdown: redcarpet
highlighter: null
redcarpet:
  extensions: ["tables"]
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

# Blog
excerpt_separator: "<!--more-->"

# Exclude Team Blog for now
exclude: ["team-blog/index.html"]
